// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <secrets.h>
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "e75c7427-a09c-4e3e-a9ce-ffcd70e3fdd7";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onCrowlStateChange();
void onJumpStateChange();

bool crowlState;
bool jumpState;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(crowlState, READWRITE, ON_CHANGE, onCrowlStateChange);
  ArduinoCloud.addProperty(jumpState, READWRITE, ON_CHANGE, onJumpStateChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
